# Generated by Django 5.2.8 on 2026-01-19 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='상품코드(영문)')),
                ('original_price', models.IntegerField(default=0, verbose_name='정가(원)')),
                ('price', models.IntegerField(verbose_name='판매가(할인가)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='대표 이미지')),
                ('description', models.TextField(blank=True, verbose_name='상품설명')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_color', models.CharField(blank=True, max_length=50, verbose_name='선택 색상')),
                ('option_size', models.CharField(blank=True, max_length=50, verbose_name='선택 사이즈')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='배송지')),
                ('contact_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('status', models.CharField(default='입금대기', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
