# Generated by Django 5.2.8 on 2026-01-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/detail/', verbose_name='기본 뒷면'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='products/detail/', verbose_name='기본 앞면'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='option_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='option_size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='입금대기', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='상품코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=0, verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='판매가'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='색상명 (예: 검정)')),
                ('image_front', models.ImageField(upload_to='products/colors/', verbose_name='앞면 이미지')),
                ('image_back', models.ImageField(blank=True, upload_to='products/colors/', verbose_name='뒷면 이미지')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
