# Generated by Django 5.2.8 on 2026-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_joinpost_author_joinpost_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpost',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처'),
        ),
        migrations.AddField(
            model_name='joinpost',
            name='password',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='비밀번호'),
        ),
    ]
