# Generated by Django 5.2.8 on 2026-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_joinpost_contact_number_joinpost_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-like_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='노출 우선순위 (높을수록 상단)'),
        ),
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='추천수'),
        ),
    ]
