# Generated by Django 5.2.8 on 2026-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_options_product_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requests',
            field=models.TextField(blank=True, null=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='-', max_length=100, verbose_name='주문자'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(max_length=50, verbose_name='색상명'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='뒷면'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_front',
            field=models.ImageField(upload_to='products/views/', verbose_name='앞면'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='왼팔'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='오른팔'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='사이즈 (예: S, 95)')),
                ('stock', models.IntegerField(default=0, verbose_name='재고수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
        ),
    ]
