# Generated by Django 5.2.8 on 2026-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_requests_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='색상 (예: White)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoption',
            name='size',
            field=models.CharField(max_length=20, verbose_name='사이즈 (예: L)'),
        ),
    ]
