# Generated by Django 5.2.8 on 2026-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productoption_color_alter_productoption_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='고객 이메일'),
        ),
    ]
