# Generated by Django 5.2.8 on 2026-02-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_partnership_business_number_alter_partnership_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('결제대기', '결제대기'), ('결제완료', '결제완료'), ('제작중', '제작중'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('주문취소', '주문취소')], default='결제대기', max_length=20, verbose_name='주문상태'),
        ),
    ]
