# Generated by Django 5.2.8 on 2025-12-22 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('short_description', models.CharField(max_length=300, verbose_name='한줄 소개')),
                ('content', models.TextField(verbose_name='상세 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='썸네일')),
                ('is_active', models.BooleanField(default=True, verbose_name='모집중 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '모집 공고',
                'verbose_name_plural': '모집 공고 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격 (원)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 목록',
            },
        ),
        migrations.CreateModel(
            name='JoinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='익명', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product', verbose_name='상품')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='재고 수량')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고 관리',
            },
        ),
        migrations.CreateModel(
            name='JoinAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.joinpost')),
            ],
        ),
        migrations.CreateModel(
            name='JoinPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qna_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.joinpost')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/details/%Y/%m/%d/', verbose_name='상세 이미지')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='표시 순서')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상세 이미지',
                'verbose_name_plural': '상세 이미지 목록',
                'ordering': ['product', 'order'],
            },
        ),
    ]
