# Generated by Django 5.2.8 on 2026-01-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_back_product_image_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/', verbose_name='상세페이지 (긴 이미지)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='왼팔 (누끼)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='오른팔 (누끼)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='대표 이미지 (썸네일)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='뒷면 (누끼)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='앞면 (누끼)'),
        ),
    ]
