# Generated by Django 5.2.8 on 2026-01-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_detail_image_product_image_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='색상명 (예: 검정, 화이트)')),
                ('color_code', models.CharField(default='#ffffff', max_length=20, verbose_name='색상코드 (예: #000000)')),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='앞면')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='뒷면')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='왼팔')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='오른팔')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
        ),
    ]
