# Generated by Django 5.2.8 on 2026-01-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcolor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_back',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_front',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_left',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_right',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color_code',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='상품설명 (짧은)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/', verbose_name='상세페이지 (공통)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='대표 썸네일'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='뒷면 (누끼)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_front',
            field=models.ImageField(default='', upload_to='products/views/', verbose_name='앞면 (누끼)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='왼팔 (누끼)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='products/views/', verbose_name='오른팔 (누끼)'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
