# Generated by Django 5.2.8 on 2026-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_back_remove_product_image_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='-', max_length=100, verbose_name='주문자/단체명'),
        ),
    ]
