# Generated by Django 5.2.8 on 2026-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productoption_color_alter_productoption_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='color',
            field=models.CharField(max_length=50, verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='size',
            field=models.CharField(max_length=20, verbose_name='사이즈'),
        ),
    ]
