# Generated by Django 5.2.8 on 2026-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, verbose_name='업체명(브랜드명)')),
                ('manager_name', models.CharField(max_length=50, verbose_name='담당자 이름')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('location', models.CharField(max_length=200, verbose_name='업체 위치')),
                ('description', models.TextField(verbose_name='입점 희망 제품/설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partnership/', verbose_name='대표 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '입점 문의',
                'verbose_name_plural': '입점 문의 목록',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='FREE', max_length=10, verbose_name='사이즈'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='송장번호'),
        ),
    ]
