# Generated by Django 5.2.8 on 2026-02-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_partnership_order_carrier_order_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자 등록번호'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partnership/main/', verbose_name='대표 사진'),
        ),
        migrations.CreateModel(
            name='PartnershipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partnership/details/', verbose_name='상세 사진')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.partnership')),
            ],
        ),
    ]
